Remove lus/pipe and add lus/yamif & cerus/maps
Paul2708/spigot-plugin-resources pull request #26
Opened 2021-10-01 20:21 UTC by lus

Hello ^^

I discontinued pipe some time ago so I removed it from this list too.
However, I "recently" created a GUI/Inventory framework called yamif, so I added it.
@cerus also recently released a nice project called `maps` which provides a nice API to create clientside Spigot maps.

PS: Thanks for this nice repository serving as a central reference for Minecraft development for some time now :D

2021-10-01 21:00 UTC, cerus commented
Please also replace `packet-maps` with `maps`

2021-10-02 07:02 UTC, Paul2708 commented
Hey! :D
Thank you for your contribution. To approve the pull request, can you order the new APIs alphabetically? That would be perfect

2021-10-02 07:03 UTC, Paul2708 requested changes
Sort APs alphabetically

2021-10-03 14:19 UTC, Paul2708 approved these changes

2021-10-03 14:19 UTC, merged